### ISSUE TITLE
is this abandoned?

### ISSUE THREAD

**Issue by goatandsheep** [facorread/yarn-chocolatey#1]
I noticed that you said we should use corepack to manage yarn instead of chocolatey. So is this project abandoned?

**Comment by facorread** [comment]
Thanks for your interest on Chocolatey! This repository is not abandoned; it is up to date with the latest version of [Yarn-1 Classic Stable](https://classic.yarnpkg.com/en/docs/install#windows-stable) and will continue to release maintenance updates through Chocolatey when they are made available upstream.

As a way of clarification to everyone, modern versions of Yarn are managed through Corepack, which is also the only officially supported [installation](https://yarnpkg.com/getting-started/install) method. There are no oficially-available binaries for download through a package manager such as Chocolatey. Everyone should seriously consider migrating to modern versions of Yarn.
