### ISSUE TITLE
Yarn 2.x support?

### ISSUE THREAD

**Issue by cowwoc** [facorread/yarn-chocolatey#2]
Hi,

I'm a long-time user of your package. Do you plan on adding Yarn 2.x support anytime soon? I'm interested in upgrading.

**Comment by facorread** [comment]
Hi @cowwoc,

There are no plans to add support to Yarn 2.x at all. I would encourage you to upgrade your projects to Yarn 3 instead. Please see #1 for reference. And thank you for your interest on this repository.

**Comment by cowwoc** [comment]
@facorread I actually meant the latest version of Yarn (and that's version 3 as you mentioned). So if I understand you correctly, you expect users to install yarn 1.x using chocolatey and then invoke `yarn set version berry` to upgrade to version 3.x?

**Comment by facorread** [comment]
@cowwoc Yes, I would expect everyone to follow the installation and migration instructions at https://yarnpkg.com/getting-started and, at your option, you can run `choco install yarn` as your first migration step.
